apiVersion: v1
kind: Pod
metadata:
  name: comment-box
spec:
  containers:
    - name: app
      image: evgeny/comment-box
      imagePullPolicy: Always
      env:
        - name: GOOGLE_CONSUMER_KEY
          value: ${GOOGLE_CONSUMER_KEY}
        - name: GOOGLE_CONSUMER_SECRET
          value: ${GOOGLE_CONSUMER_SECRET}
        - name: GOOGLE_CALLBACK
          value: http://commentbox.cf
      ports:
        - containerPort: 3000
          hostPort: 80
    - name: mongo
      image: mongo
      volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
  volumes:
    - name: mongo-persistent-storage

